var varity = [
    "202 ½ इंच चौकोर",
    "202 रेगुलर चौकोर",
    "202 ½ इंच गोल",
    "202 रेगुलर गोल",
    "304 ½ इंच चौकोर",
    "304 रेगुलर चौकोर",
    "304 ½ इंच चौकोर",
    "304 रेगुलर चौकोर",
    "Angle",
    "Angle 1x1",
    "Angle 1¼x1",
    "Angle 35x5",
    "Angle 40x5",
    "Angle 40x6",
    "Angle 50x5",
    "Angle 50x6",
    "Angle 65x5",
    "Angle 65x6",
    "H/W 202",
    "H/W 304",
    "Jaali",
    "Jindal 600fe 2½ सूत",
    "Jindal 600fe 3 सूत",
    "Jindal 600fe 4 सूत",
    "Jindal 600fe 5 सूत",
    "Jindal 600fe 20mm",
    "Jindal 600fe 22mm",
    "Jindal 600fe 25mm",
    "Patti",
    "Patti ¾ x 1¼",
    "Patti ¾ x 1½",
    "Patri 1x1",
    "Patri 1x2",
    "Pipe टाटा",
    "Pipe JDS",
    "Pipe लोकल",
    "Pipe अपोलो",
    "RHL रिंग 7x3",
    "RHL रिंग 7x7",
    "RHL 2½ सूत",
    "RHL 3 सूत",
    "RHL 4 सूत",
    "RHL 5 सूत",
    "RHL 20mm",
    "RHL 22mm",
    "RHL 25mm",
    "Ring",
    "Round",
    "Round 2 सूत",
    "Round 5 सूत",
    "Saria",
    "Sheet",
    "Sheet नालीदार",
    "Square",
    "Square 2 सूत",
    "Square 2½ सूत",
    "Square 3 सूत",
    "Square 4 सूत",
    "Square 5 सूत",
    "Tak 2½ सूत",
    "Tak 2 सूत",
    "T",
    "Wire लोकल",
    "Wire RHL",
    "Z"
];
